spring:
  application:
    name: webhook_processor_4_9

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_callbacks_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    ru.savin.webhook_processor_4_9: DEBUG
    feign.Client: DEBUG

app:
  http:
    client:
      transaction-service: "http://localhost:9999"

server:
  port: 8002

resilience4j.retry:
  instances:
    transactionService:
      maxAttempts: 3
      waitDuration: 1s
      retryExceptions:
        - java.net.ConnectException
        - java.net.SocketTimeoutException
        - org.springframework.web.client.ResourceAccessException
        - feign.RetryableException
        - feign.FeignException